/* ==================== Fase 4 · Mejora #21 "reporte-semanal" ====================
   Informe semanal para la familia: resumen local (HTML y texto plano)
   DESCARGABLE y COMPARTIBLE (Web Share API cuando el navegador lo ofrece),
   generado 100% en el dispositivo a partir de profile.ev[] — sin backend,
   sin red, funciona bajo file://.

   El envío por CORREO queda GATEADO (window.PEQUE_FLAGS.weeklyReportEmail,
   OFF por defecto, mismo mecanismo que window.PEQUE_FLAGS.backendSync ya
   documentado en docs/backend-supabase.md): emailReport() nunca hace
   fetch/XHR mientras el flag esté apagado. Ver integration.md → "Contrato:
   envío por correo (GATED)" para el diseño de activación futura.

   Patrón 100% aditivo (igual que AudioBank / bilingüe / co-juego / álbum de
   logros ya integrados en ship/app.js):
   - Envuelve window.logRound por reasignación para sellar profile.ev[].ts
     (timestamp) en cada evento NUEVO — campo aditivo, no cambia la forma
     {g,k,ft,at,ms,as} que ya leen aggregate()/renderProgress2()/eduBody/CSV.
     Los eventos previos a esta mejora simplemente no tienen .ts y se excluyen
     del cálculo semanal (no se puede saber cuándo ocurrieron).
   - Envuelve window.renderProgress2 por reasignación para pintar una caja
     nueva (#weeklyReportBox) inmediatamente después de #progBody, dentro de
     #progView (pestaña "Progreso" ya gateada). No reescribe su cuerpo.
   - i18n aditivo con Object.assign(UI.es,{...}) / Object.assign(UI.en,{...}).
   - addEventListener sobre #langBtn (nunca reasigna su .onclick) para
     refrescar los textos si el panel ya está abierto.
   - No toca init() ni applyLang(). No anima nada (solo texto/botones
     estáticos reutilizando .btn.ghost del core) — nada que reduzca por
     prefers-reduced-motion.
   Evidencia: NAEYC 2022 / AAP (co-juego con un adulto) — el informe está
   pensado para conversarse en familia, no para "rankear" al niño. */
(function(){
  "use strict";

  /* ---------- i18n aditivo (no toca literales UI.es/UI.en existentes) ---------- */
  if(typeof UI==='object' && UI.es && UI.en){
    Object.assign(UI.es, {
      wrTitle:'Informe semanal',
      wrSub:'Resumen de los últimos 7 días, para compartir en familia.',
      wrPeriod:'Semana del {a} al {b}',
      wrStarsWeek:'Estrellas esta semana',
      wrRoundsWeek:'Rondas esta semana',
      wrByGame:'Por materia',
      wrNoData:'Aún no hay actividad esta semana. ¡A jugar!',
      wrFooter:'Generado por Pequeñautas el {date}',
      wrDownloadHtml:'Descargar informe',
      wrDownloadTxt:'Descargar como texto',
      wrShare:'Compartir'
    });
    Object.assign(UI.en, {
      wrTitle:'Weekly report',
      wrSub:'Summary of the last 7 days, to share with family.',
      wrPeriod:'Week of {a} to {b}',
      wrStarsWeek:'Stars this week',
      wrRoundsWeek:'Rounds this week',
      wrByGame:'By subject',
      wrNoData:'No activity yet this week. Let’s play!',
      wrFooter:'Generated by Pequeñautas on {date}',
      wrDownloadHtml:'Download report',
      wrDownloadTxt:'Download as text',
      wrShare:'Share'
    });
  }

  /* ---------- sellado de timestamp (wrap de window.logRound) ---------- */
  function wrStampLast(){
    var p = (typeof currentProfile==='function') ? currentProfile() : null;
    if(!p || !p.ev || !p.ev.length) return;
    var last = p.ev[p.ev.length-1];
    if(last && last.ts==null){ last.ts = Date.now(); if(typeof saveDB==='function') saveDB(); }
  }
  if(!window.__weeklyReportLogWrapped){
    window.__weeklyReportLogWrapped = true;
    var _logRound = window.logRound;
    if(typeof _logRound === 'function'){
      window.logRound = function(){
        var r = _logRound.apply(this, arguments);
        try{ wrStampLast(); }catch(e){}
        return r;
      };
    }
  }

  /* ---------- ventana semanal + agregación (paralela a aggregate(), acotada) ---------- */
  var DAY_MS = 24*60*60*1000;
  function weekRange(atMs){
    atMs = (typeof atMs==='number') ? atMs : Date.now();
    return { start: atMs - 6*DAY_MS, end: atMs }; // últimos 7 días, hoy incluido
  }
  function weeklyEvents(p){
    if(!p || !p.ev) return [];
    var r = weekRange();
    return p.ev.filter(function(e){ return typeof e.ts==='number' && e.ts>=r.start && e.ts<=r.end; });
  }
  function weeklyAggregate(p){
    var ev = weeklyEvents(p);
    var rounds = ev.length;
    var first = ev.filter(function(e){ return e.ft; }).length;
    var avg = rounds ? ev.reduce(function(s,e){ return s+e.ms; },0)/rounds : 0;
    var byGame = { math:{r:0,err:0}, reading:{r:0,err:0}, science:{r:0,err:0} };
    var fails = {};
    ev.forEach(function(e){
      var g = byGame[e.g]; if(g){ g.r++; if(e.at>1 || e.as) g.err++; }
      if(e.at>1){ fails[e.k] = (fails[e.k]||0) + (e.at-1); }
    });
    var topFails = Object.keys(fails).map(function(k){ return {k:k,c:fails[k]}; })
      .sort(function(a,b){ return b.c-a.c; }).slice(0,3);
    /* Cada evento de profile.ev sólo se registra en afterCorrect() (ronda
       acertada), así que rounds===estrellas ganadas esta semana. */
    return { rounds:rounds, firstRate: rounds?first/rounds:0, avg:avg, byGame:byGame, topFails:topFails, stars:rounds };
  }
  function faceOf(k){
    if(typeof eduFaceOf==='function'){ try{ return eduFaceOf(k); }catch(e){} }
    return k;
  }
  function fmtDate(ts, lang){
    try{ return new Date(ts).toLocaleDateString(lang==='es'?'es-ES':'en-US', {day:'2-digit', month:'short'}); }
    catch(e){ return ''; }
  }
  function esc(s){
    if(typeof eduEsc==='function') return eduEsc(s);
    return String(s==null?'':s).replace(/[&<>"]/g,function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]; });
  }

  /* ---------- construcción del informe (texto plano) ---------- */
  function buildText(p, lang){
    var t = UI[lang] || UI.es;
    var r = weekRange();
    var a = weeklyAggregate(p);
    var lines = [];
    lines.push(t.wrTitle + ' — ' + p.name);
    lines.push(t.wrPeriod.replace('{a}', fmtDate(r.start, lang)).replace('{b}', fmtDate(r.end, lang)));
    lines.push('');
    if(a.rounds===0){
      lines.push(t.wrNoData);
    } else {
      lines.push('⭐ ' + t.wrStarsWeek + ': ' + a.stars);
      lines.push('🔁 ' + t.wrRoundsWeek + ': ' + a.rounds);
      lines.push('🎯 ' + t.stFirst + ': ' + Math.round(a.firstRate*100) + '%');
      lines.push('⏱ ' + t.stTime + ': ' + (a.avg/1000).toFixed(1) + 's');
      lines.push('');
      lines.push(t.wrByGame + ':');
      ['math','reading','science'].forEach(function(g){
        var gg = a.byGame[g]; if(gg.r>0){
          var acc = Math.round((1-gg.err/gg.r)*100);
          var nm = g==='math'?t.math:(g==='reading'?t.read:t.sci);
          lines.push('  - ' + nm + ': ' + gg.r + ' · ' + acc + '% ' + t.mAcc.toLowerCase());
        }
      });
      if(a.topFails.length){
        lines.push('');
        lines.push(t.stFocus + ':');
        a.topFails.forEach(function(f){ lines.push('  - ' + faceOf(f.k) + ' (' + f.c + '✗)'); });
      }
    }
    lines.push('');
    lines.push(t.wrFooter.replace('{date}', new Date().toLocaleDateString(lang==='es'?'es-ES':'en-US')));
    return lines.join('\n');
  }

  /* ---------- construcción del informe (HTML autocontenido, sin red) ---------- */
  function buildHTML(p, lang){
    var t = UI[lang] || UI.es;
    var r = weekRange();
    var a = weeklyAggregate(p);
    function stat(icon, n, label){
      return '<div class="stat"><div class="n">' + icon + ' ' + esc(String(n)) + '</div><div class="l">' + esc(label) + '</div></div>';
    }
    var body;
    if(a.rounds===0){
      body = '<p class="empty">' + esc(t.wrNoData) + '</p>';
    } else {
      var bars = '';
      ['math','reading','science'].forEach(function(g){
        var gg = a.byGame[g]; if(gg.r>0){
          var acc = Math.round((1-gg.err/gg.r)*100);
          var nm = g==='math'?t.math:(g==='reading'?t.read:t.sci);
          var col = g==='math'?'#4EA8DE':(g==='reading'?'#F2748C':'#57C596');
          bars += '<div class="bar"><div class="lab"><span>' + esc(nm) + '</span><span>' + acc + '%</span></div>' +
            '<div class="track"><div class="fill" style="width:' + acc + '%;background:' + col + '"></div></div></div>';
        }
      });
      var fails = '';
      if(a.topFails.length){
        fails = '<h3>' + esc(t.stFocus) + '</h3><ul class="fails">' +
          a.topFails.map(function(f){ return '<li>' + esc(faceOf(f.k)) + ' <span class="c">' + f.c + ' ✗</span></li>'; }).join('') +
          '</ul>';
      }
      body = '<div class="stats">' + stat('⭐', a.stars, t.wrStarsWeek) + stat('🔁', a.rounds, t.wrRoundsWeek) +
        stat('🎯', Math.round(a.firstRate*100)+'%', t.stFirst) + stat('⏱', (a.avg/1000).toFixed(1)+'s', t.stTime) + '</div>' +
        (bars ? ('<h3>' + esc(t.wrByGame) + '</h3>' + bars) : '') + fails;
    }
    return '<!DOCTYPE html><html lang="' + lang + '"><head><meta charset="UTF-8">' +
      '<meta name="viewport" content="width=device-width, initial-scale=1.0">' +
      '<title>' + esc(t.wrTitle) + ' — ' + esc(p.name) + '</title>' +
      '<style>' +
        'body{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;background:#FDF6EC;color:#3B3355;margin:0;padding:28px;}' +
        '.card{max-width:560px;margin:0 auto;background:#fff;border-radius:24px;box-shadow:0 10px 30px rgba(59,51,85,.12);padding:26px;}' +
        'h1{font-size:22px;margin:0 0 4px;}.sub{color:#6C6685;font-size:14px;margin:0 0 18px;}' +
        '.stats{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:12px;}' +
        '.stat{background:#F8F6FD;border-radius:14px;padding:12px;}.stat .n{font-size:19px;font-weight:700;}.stat .l{font-size:12px;color:#6C6685;}' +
        'h3{font-size:13px;color:#6C6685;margin:16px 0 6px;text-transform:uppercase;letter-spacing:.03em;}' +
        '.bar{margin-top:8px;}.bar .lab{display:flex;justify-content:space-between;font-size:13px;font-weight:600;margin-bottom:4px;}' +
        '.bar .track{height:10px;border-radius:6px;background:#EEE9F6;overflow:hidden;}.bar .fill{height:100%;border-radius:6px;}' +
        '.fails{list-style:none;padding:0;margin:0;}.fails li{display:flex;justify-content:space-between;padding:6px 0;border-top:1px solid #F0ECF6;font-size:14px;}' +
        '.fails .c{color:#F2748C;font-weight:600;}.empty{color:#6C6685;font-size:14px;}' +
        'footer{margin-top:18px;font-size:11.5px;color:#9992ac;text-align:center;}' +
      '</style></head><body><div class="card">' +
      '<h1>' + esc(t.wrTitle) + ' · ' + esc(p.avatar) + ' ' + esc(p.name) + '</h1>' +
      '<p class="sub">' + esc(t.wrPeriod.replace('{a}', fmtDate(r.start, lang)).replace('{b}', fmtDate(r.end, lang))) + '</p>' +
      body +
      '<footer>' + esc(t.wrFooter.replace('{date}', new Date().toLocaleDateString(lang==='es'?'es-ES':'en-US'))) + '</footer>' +
      '</div></body></html>';
  }

  function slug(s){
    return String(s||'peque').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'')
      .replace(/[^a-zA-Z0-9]+/g,'-').toLowerCase().replace(/(^-|-$)/g,'') || 'peque';
  }
  function triggerDownload(filename, content, mime){
    try{
      var blob = new Blob([content], {type: mime});
      var url = URL.createObjectURL(blob);
      var a = document.createElement('a'); a.href=url; a.download=filename;
      document.body.appendChild(a); a.click(); a.remove();
      setTimeout(function(){ URL.revokeObjectURL(url); }, 1000);
      return true;
    }catch(e){ return false; }
  }
  function downloadHTML(p){
    p = p || (typeof currentProfile==='function' ? currentProfile() : null); if(!p) return false;
    var lang = (typeof S==='object' && S) ? S.lang : 'es';
    return triggerDownload('pequenautas-informe-'+slug(p.name)+'.html', buildHTML(p, lang), 'text/html;charset=utf-8');
  }
  function downloadText(p){
    p = p || (typeof currentProfile==='function' ? currentProfile() : null); if(!p) return false;
    var lang = (typeof S==='object' && S) ? S.lang : 'es';
    return triggerDownload('pequenautas-informe-'+slug(p.name)+'.txt', buildText(p, lang), 'text/plain;charset=utf-8');
  }
  function canShare(){ return typeof navigator!=='undefined' && typeof navigator.share==='function'; }
  function share(p){
    p = p || (typeof currentProfile==='function' ? currentProfile() : null); if(!p) return Promise.resolve(false);
    if(!canShare()) return Promise.resolve(false);
    var lang = (typeof S==='object' && S) ? S.lang : 'es';
    var t = UI[lang] || UI.es;
    return navigator.share({ title: t.wrTitle+' · '+p.name, text: buildText(p, lang) })
      .then(function(){ return true; }).catch(function(){ return false; });
  }

  /* ---------- CONTRATO GATED: envío por correo (OFF, sin red en runtime) ----------
     Mismo mecanismo que window.PEQUE_FLAGS.backendSync (docs/backend-supabase.md):
     el flag por defecto es false y esta función NUNCA hace fetch/XHR mientras
     esté apagado — resuelve de inmediato con {ok:false, reason:'gated'}. Ver
     integration.md → "Contrato: envío por correo (GATED)" para el diseño de
     activación (edge function + consentimiento + proveedor de correo). */
  window.PEQUE_FLAGS = Object.assign({ weeklyReportEmail:false }, window.PEQUE_FLAGS||{});
  function emailReport(p, opts){
    opts = opts || {};
    if(!window.PEQUE_FLAGS || !window.PEQUE_FLAGS.weeklyReportEmail){
      return Promise.resolve({ ok:false, reason:'gated' });
    }
    /* Inalcanzable mientras el flag esté OFF (siempre lo está por defecto).
       No implementar un fetch real aquí sin consentimiento verificado del
       adulto y sin revisar docs/backend-supabase.md (RLS, minimización de
       datos, retención). */
    return Promise.resolve({ ok:false, reason:'not_implemented' });
  }

  /* ---------- UI: caja nueva dentro de #progView, hermana de #progBody ---------- */
  function ensureBox(){
    var host = $('progView'); if(!host) return null;
    var box = $('weeklyReportBox');
    if(!box){
      box = document.createElement('div'); box.className='wrBox'; box.id='weeklyReportBox';
      box.innerHTML =
        '<div class="wrHead"><span class="wrIcon" aria-hidden="true">🗓️</span>' +
          '<div><div class="wrTitle" id="wrTitle"></div><div class="wrSub" id="wrSub"></div></div></div>' +
        '<div class="wrStatsLine" id="wrStatsLine"></div>' +
        '<div class="wrActions">' +
          '<button class="btn ghost wrBtn" id="wrDownloadBtn" type="button"><span id="wrDownloadHtmlLbl"></span></button>' +
          '<button class="btn ghost wrBtn" id="wrDownloadTxtBtn" type="button"><span id="wrDownloadTxtLbl"></span></button>' +
          '<button class="btn ghost wrBtn" id="wrShareBtn" type="button" hidden><span id="wrShareLbl"></span></button>' +
        '</div>';
      var body = $('progBody');
      if(body && body.parentNode===host) body.insertAdjacentElement('afterend', box);
      else host.appendChild(box);
      $('wrDownloadBtn').addEventListener('click', function(){ downloadHTML(); });
      $('wrDownloadTxtBtn').addEventListener('click', function(){ downloadText(); });
      $('wrShareBtn').addEventListener('click', function(){ share(); });
    }
    return box;
  }
  function render(){
    var box = ensureBox(); if(!box) return;
    var lang = (typeof S==='object' && S) ? S.lang : 'es';
    var t = UI[lang] || UI.es;
    var p = (typeof currentProfile==='function') ? currentProfile() : null;
    var set = function(id, txt){ var el=$(id); if(el && txt!=null) el.textContent=txt; };
    set('wrTitle', t.wrTitle); set('wrSub', t.wrSub);
    set('wrDownloadHtmlLbl', t.wrDownloadHtml); set('wrDownloadTxtLbl', t.wrDownloadTxt); set('wrShareLbl', t.wrShare);
    var shareBtn = $('wrShareBtn'); if(shareBtn) shareBtn.hidden = !canShare();
    var line = $('wrStatsLine');
    if(line){
      if(!p){ line.textContent=''; }
      else {
        var a = weeklyAggregate(p);
        line.textContent = a.rounds>0
          ? ('⭐ ' + a.stars + ' · 🔁 ' + a.rounds + ' · 🎯 ' + Math.round(a.firstRate*100) + '%')
          : t.wrNoData;
      }
    }
  }

  /* ---------- wrap de window.renderProgress2 (cadena de responsabilidad, mismo
     mecanismo que window.refreshHome en #09-recomendador) ---------- */
  if(!window.__weeklyReportUIWrapped){
    window.__weeklyReportUIWrapped = true;
    var _renderProgress2 = window.renderProgress2;
    if(typeof _renderProgress2 === 'function'){
      window.renderProgress2 = function(){
        var r = _renderProgress2.apply(this, arguments);
        try{ render(); }catch(e){}
        return r;
      };
    }
  }

  /* Idioma en vivo si el panel de Progreso ya está abierto (addEventListener,
     nunca reasigna #langBtn.onclick, para no romper la cadena existente). */
  var lb = $('langBtn');
  if(lb && !lb._wrWired){
    lb._wrWired = true;
    lb.addEventListener('click', function(){
      var pv = $('progView');
      if(pv && pv.style.display!=='none') render();
    });
  }

  /* API pública para tests/tooling. */
  window.__weeklyReport = {
    weekRange: weekRange,
    weeklyEvents: weeklyEvents,
    weeklyAggregate: weeklyAggregate,
    buildHTML: buildHTML,
    buildText: buildText,
    downloadHTML: downloadHTML,
    downloadText: downloadText,
    canShare: canShare,
    share: share,
    emailReport: emailReport,
    render: render
  };
})();
